### ISSUE TITLE
Radosgw container migrate to another server 

### ISSUE THREAD

**Issue by JoshuaAndrew** [ceph/ceph-docker#111]
As we know.  Radosgw container is the gateway of  Ceph on CoreOS Cluster,the Radosgw container
sometimes migrate to another server . How to solve this  issues?

**Comment by leseb** [comment]
I don't understand what you meant, can you elaborate a bit more?

**Comment by Ulexus** [comment]
@JoshuaAndrew If I understand you correctly, you are concerned about the radosgw container migrating across your cluster on restarts.  This problem is not unique to the Ceph containers; thus, there are many options available to you.

  * Service discovery - This usually the best option, and there are many choices.  Since you are running CoreOS, you have `etcd` already included.  See the section on service discovery on CoreOS's [site](https://coreos.com/docs/quickstart/).
  * Static service IP, bound at start - For some services, I assign the service a static IP address, which I float with the service.  Essentially, I add and remove the IP address from the host if and only if the service starts on that host.
  * Restrict the service to run only on a single host (or a small group of hosts).  This is _not_ a good idea for redundancy, but it is _easy_.  If you are using fleet, just specify the machine id or other metadata in the unit file, as described [here](https://coreos.com/docs/launching-containers/launching/fleet-unit-files/).

... and probably many more.  Use service discovery if possible, though.

**Comment by Ulexus** [comment]
Closing this for now, as it does not appear to be a problem related to this repository.
