### ISSUE TITLE
Support CRUSH locations

### ISSUE THREAD

**Issue by Ulexus** [ceph/ceph-docker#121]
Spawned by discussion from #113 

CRUSH location types [http://ceph.com/docs/master/rados/operations/crush-map/](http://ceph.com/docs/master/rados/operations/crush-map/):
```
type 0 osd
type 1 host
type 2 chassis
type 3 rack
type 4 row
type 5 pdu
type 6 pod
type 7 room
type 8 datacenter
type 9 region
type 10 root
```

I think we should offer a free-form CRUSH_LOCATION for "experts," but we should also offer each of the types explicitly (ex. CRUSH_RACK), whose purpose and use should be more easily-grasped, though such may be more verbose.

**Comment by leseb** [comment]
@Ulexus yes it's a restricted set but using several variables for each type might be really lengthy and will provide the exact same thing. Type are not going to change anytime soon, I don't think new type will come up either BUT having a single variable will be more flexible.
Thus we give the freedom to the users to build their own location.

If we go with `CRUSH_ROOT`, `CRUSH_REGION`, `CRUSH_DATACENTER` etc etc we will have an entrypoint like this:

`root=$CRUSH_ROOT region=$CRUSH_REGION  datacenter=$CRUSH_DATACENTER host=$(hostname)`.

In the situation where region is not (simply not required by the operator) set we have to come up with a default value to not  this will also add unnecessary complexity to the crush map.
We could also have a set of `if` statements to check if the variable is empty or not and if so remove it from the command line. But we agree that's a terrible solution.

That's why I prefer to use:

`CRUSH_LOCATION='root=default datacenter=dc1 room=1 rack=10 host=$(hostname)'`

This will let the user decide and will remove complex solutions in the entrypoint.
It can even be as simple as that:

`CRUSH_LOCATION='root=default  host=$(hostname)'`, and this will likely be the default for the `CRUSH_LOCATION` variable.

**Comment by Ulexus** [comment]
@leseb  I don't know what I was thinking.  If the user can read enough to get the environment variable names, they can read enough to get the list of options.  Yes, the free-form `CRUSH_LOCATION` makes much more sense.

**Comment by tangzhankun** [comment]
hi @leseb,
I think put all bucket type and value in a CRUSH_LOCATION is good. 
And here I have a question on the use case of ceph/daemon:
what's the goal of ceph/daemon? A unified docker images for all daemons?

**Comment by leseb** [comment]
@tangzhankun the ceph/daemon contains all the Ceph daemons, it just allows you to enable the one you want. You can only run one daemon per container. If you want a container with all the daemons running you should look at ceph/demo.
