### ISSUE TITLE
Switching to ceph/daemon and/or ceph/config

### ISSUE THREAD

**Issue by hookenz** [ceph/ceph-docker#136]
@leseb - for the impatient (that's me ;) are you able to update the readme for those wishing to switch from ceph/mon, ceph/osd to ceph/daemon?

I take it that ceph/osd, ceph/mon etc will be removed at some point in the near future.
Also, I think it might be worthwhile using ceph/config, how would you go about transitioning to this from a static config?

**Comment by leseb** [comment]
@hookenz yes I can think of a migration path or at least some recommendations on how to move.
I don't think we have anybody really using ceph/config anyway (are you using it?). It was mostly a first attempt to store configs in kv stores. This work is now embedded into ceph/daemon which has most of the knowledge on how to store config in a KV store.

**Comment by hookenz** [comment]
@leseb - I'm not using ceph/config but I would like to migrate to ceph/daemon.

**Comment by leseb** [comment]
@hookenz what are you using at the moment?

**Comment by hookenz** [comment]
@leseb - a static config.  On service nodes of which there are only 8 currently (mon/mds, other databases and services etc), I've just copied my /etc/ceph directories around manually on the nodes that matter.  My compute nodes which are also OSD's get the /etc/ceph populated through cloud-init.  These are netbooted.

**Comment by leseb** [comment]
@hookenz I think we might have to perform some tests on rebooting containers.
I have @h0tbird has been pushing some patches around that. I'll see if I can find some time to test the stop/start of each containers.
Ultimately the idea will be keep the data and configs directories (`/var/lib/ceph` and `/etc/ceph/ceph`).
Then re-use the same arguments to bootstrap the new containers.

As soon as they all support stop/start this procedure should work.
@h0tbird any further comments?

**Comment by h0tbird** [comment]
I am using `ceph/daemon` in combination with `etcd` as a KV backend.
My short term goal is to deploy a Ceph storage cluster (`mon` and `osd` only).
I have committed a few patches in order to make this 2 components reboot-aware.
Since my configuration lives in `etcd` I don’t really need to mount `/etc/ceph` on the host.
I am using `CoreOS` and `fleetd` to run my containers.

**Comment by hookenz** [comment]
Cool! In my case, I decided not to use fleet to schedule osd's but rather start them in cloud-config.  I also had trouble using fleet with mds so that's also static.

**Comment by Ulexus** [comment]
@hookenz Things _should_ just work by running `ceph/daemon <daemonname>` instead of `ceph/<daemonname>`.  For the most part, the script pieces were just copied over wholesale.  KV support was _added_, but all the daemons _should_ be backward compatible with the flat files.  OSDs in particular, I made sure to have the default be using the existing directory structure.

I'm also curious as to your issues with `mds` and fleet.  That's exactly what I use, and I've had no problems.

**Comment by hookenz** [comment]
@Ulexus - I was concerned that fleet kept moving my mds around and if I'm not mistaken mds metadata can't float around?  I was having issues with fleet at the time because I was switching from the containerized etcd2 to the CoreOS native etcd2.  That might have had something to do with it.  

I suppose the question is can the MDS just be shut down and started elsewhere or do you need to run a hot standby for that to happen.  If you completely lost the mds and started a new one would you loose your metadata?

**Comment by Ulexus** [comment]
@hookenz  - MDS (very unlike MON and OSD) is happy to roam around the cluster.  That's exactly how mine is configured.  I have `mds@a.service`, which can be bumped from machine to machine at will.  I've had no problems with it doing so, and while ceph now does allow multiple mds instances, I just use one on my cluster.

**Comment by hookenz** [comment]
@Ulexus - thanks for that clarification.
