### ISSUE TITLE
user_xattr

### ISSUE THREAD

**Issue by lorieri** [ceph/ceph-docker#145]
the demo container requires user_xattr

I was going to update the readme with a remount example but I'm not sure the best way to do it

something like this:
```
 sudo mount -o remount,user_xattr,rw /var
```

**Comment by Ulexus** [comment]
Perhaps I'm blind (I haven't actually run the demo), but I don't see anything in there which requires extended attributes.

**Comment by leseb** [comment]
I'm not getting this one either...
@lorieri do you mean that the partition where Ceph will run need `user_xattr` and thus we should put this as a recommendation?
I believe then that this is not only valid for the demo but also the daemon and osd images.

**Comment by lorieri** [comment]
When I run the Demo following the instructions at docker hub it fails and shows a user_xattr error, re-mounting the partition make it works.

**Comment by leseb** [comment]
Hum never faced that problem before perhaps my fs has user_xattr enabled by default, can't tell.
Feel free to update the README :)

Thanks for reporting this @lorieri

**Comment by lorieri** [comment]
I'm afraid the remount could be dangerous, I'm not sure how to say it, but let me try :)

**Comment by Ulexus** [comment]
I don't know why extended attributes would be required.  I can say for certain that none of my live Ceph systems have filesystems mounted with the `user_xattr` flag.

What storage backend are you using for Docker?  Perhaps that is the issue?  Do you know which component is requiring the extended attributes?

**Comment by butonic** [comment]
hm ... according to http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=ea6633369458992241599c9d9ebadffaeddec164 user_xattr is enabled by default since 2011.

The problem is rather an issue with AUFS: https://github.com/docker/docker/issues/6980 The only workaround seems to be to fall back to devicemapper, which is recommended anyway, see [2.7 Do not use the aufs storage driver (Scored)](https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.6_Benchmark_v1.0.0.pdf)

At least here the tip did not help ...

**Comment by butonic** [comment]
better recommendetions semm to be https://github.com/docker/docker/issues/1070#issuecomment-20624664

**Comment by Ulexus** [comment]
@butonic : Agreed, for many reasons.  No one should be using the AUFS backend anymore, if at all possible.  @lorieri , if that's the case for you, try another filesystem/backend.

**Comment by lorieri** [comment]
merger
