### ISSUE TITLE
OSD Restart

### ISSUE THREAD

**Issue by aga20** [ceph/ceph-docker#160]
Hello! When I want to try restart an OSD node after a WM fail it bootstrapped again and attach a new OSD node to the cluster. Have we got any option to restart OSD container without remove it from the cluster and bootstrapped again? I'm using daemon.

**Comment by leseb** [comment]
Hum which scenario are you using for the OSD?
Do you still use the same physical disks for the OSDs?

**Comment by h0tbird** [comment]
Do the contents of `/var/lib/ceph/` survive after the VM restart?

**Comment by Ulexus** [comment]
If `/var/lib/ceph/` is declared as an external volume and bind-mounted, then this will depend on the host.  If it is left up to Docker to figure out how to handle it (volume or no), it will be tied to the lifecycle of the _container_.  In this case, you can restart the host and it will still be present if and only if the container is not destroyed (either by the `--rm` option to `docker run` or subsequently by `docker rm`).

Note that running `/var/lib/ceph/*` directories _not_ in a volume (preferably bind-mounted) is a very bad idea, since that would make those directories layered.

**Comment by aga20** [comment]
Hi! Sorry for late reply. I found my mistake so I close this :)
