### ISSUE TITLE
Add necessary things for rgw in base or build a new one for rgw only?

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-docker#17]
I don't really the idea of having apache running on MON/OSD/MDS.
But having 2 base (even if one is named for rgw) is not really sophisticated.

I'm more in favour of new image for RGW base.

@Ulexus what do you think?

**Comment by leseb** [comment]
@Ulexus Can you test this? https://registry.hub.docker.com/u/ceph/base-rgw/ with #18

**Comment by Ulexus** [comment]
@leseb There's no need for another base, since apache et al are installed specifically for the purpose of radosgw and are not really a reusable component.  Just put the apache installation (apt-get install ...) into the radosgw Dockerfile.  (I don't see the base-rgw on the Github side, so I can't see what's in it)

Also, I don't _think_ you should have to run with `--net=host`.  The issue with the MON and OSD containers and `--net=host` (if I recall correctly) is that ceph is really picky about the IP addresses.  radosgw isn't much more than a client proxy, as I understand it, so it shouldn't matter if it runs on a different IP... is that assumption correct?

**Comment by leseb** [comment]
Ok I'll simply re-use base and install the necessary component for radosgw.
Correct the issue is with the MONs where they can't work behind a NAT.
Ending up with these kind of messages: 
```
.connect claims to be [::1]:6804/1031425 not [::1]:6804/31537 - wrong node!
```

**Comment by Ulexus** [comment]
base: Yeah, that's exactly what I was meaning

nat:  Okay, that makes sense.  `--net=host` it is.

**Comment by Ulexus** [comment]
Also, you'll probably want to run apache directly (or with supervised or similar) rather than the default Debian init scripts.  You don't want to run the whole init system for just Apache and radosgw

**Comment by leseb** [comment]
Ok will run apache from the cli, not really familiar with supervised.
Pushing a version in a couple of minutes.

**Comment by Ulexus** [comment]
Sorry, misnamed it:  [supervisord](http://supervisord.org/)

I've never actually used it myself, as I try to avoid containers running multiple daemons.  In this case, though, it doesn't really make sense to split up apache and radosgw.  Many people in the Docker world use it.  [monit](http://mmonit.com/monit/) is also reasonably common, and I _have_ used it.

In either case, the idea is that the execution blocks on a single command.  Otherwise, you have to run one process in the background, and if it dies, you (and Docker) won't know about it.  Hence, you want to use _some_ sort of light-weight process manager when running multiple daemons inside a Docker container.

**Comment by Ulexus** [comment]
I should also mention that monit has the advantage of being in the Debian (and Ubuntu) package system already, so it is just an `apt-get` away.

**Comment by Ulexus** [comment]
Also, I'll have some time next week to tidy it up (wrap it in a monitor, rearrange build options, etc) if you want to push what you've got over the weekend.

**Comment by leseb** [comment]
Great thanks :)

**Comment by Ulexus** [comment]
Merged

**Comment by Ulexus** [comment]
I just wrapped the radosgw in a monitor, and the build is up on Docker Hub, so I think we're done, here.
