### ISSUE TITLE
Slow request after restart

### ISSUE THREAD

**Issue by aga20** [ceph/ceph-docker#170]
Hello!

We want to use your solution as a docker registry backend. We need only 3 replicated node, so we have 3 monitor and osd. We use etcd too so we store datas in a kv backed (for test I use your populate.sh example). It works good until we don't restart the 3 node at same time. In this case I got slow request message when I want to try for example a docker pull from registry. The another intressting thing the cluster health is ok. After I restart all 3 osd  node it works good again. I really dissapointed because I spent many times to find the bug but I haven't any ide what is the problem.
Maybe this is not an issue but I hope you have an idea.

Platform: RedHat7 and cloud
Docker version: I try it with 1.8.2 and 1.9.1

**Comment by leseb** [comment]
Do you use `pid=host` to run your OSD?

**Comment by aga20** [comment]
No. It can help me maybe or why?

**Comment by leseb** [comment]
Yes it will. OSDs are really instable without this flag. I'll update the doc to reflect that.

**Comment by aga20** [comment]
Thanks for your help, it seems working fine now after ~5 restart.

**Comment by leseb** [comment]
@aga20 np np :)

**Comment by nazar-pc** [comment]
@leseb, I think it is a terrible idea to pass `--pid=host` because it will allow container to do literally anything with host system. This is not the capability OSDs need to have.

The root of issue should be found and fixed, until then this issue is not resolved.
Situation is especially bad because you've added this anti-recommendation to readme.

**Comment by leseb** [comment]
@nazar-pc I understand your concern and it makes sense. However until the shared PID namespace option gets merged in Docker we don't really have the choice.

**Comment by nazar-pc** [comment]
Can you clarify how `--pid=host` actually solves this issue?

**Comment by Ulexus** [comment]
It allows all of the OSDs to share a PID namespace (specifically, the host's PID namespace).

If the OSDs do not share their PID namespace, port exhaustion will rapidly ensue.

**Comment by Ulexus** [comment]
I should note that it doesn't matter if there is only a single OSD per host.

**Comment by nazar-pc** [comment]
I'm not too familiar with such kind of issues, but there must be an alternative way to resolve the issue.
I was able to find article about similar issue in HAProxy blog: http://blog.haproxy.com/2012/12/12/haproxy-high-mysql-request-rate-and-tcp-source-port-exhaustion/
Also there are some Docker-specific suggestions here: https://github.com/docker/docker/issues/2842
I think mentioned solutions should help to fix an issue in proper way. Can anyone try them?

**Comment by Ulexus** [comment]
@nazar-pc You can see the original discussion: #19

This is not a problem with the TCP port timeout, `CLOSE_WAIT` state timeouts, etc.  The port exhaustion takes _seconds_ irrespective of load.  It is a problem of the OSDs walking on each other.  They appear to have some port-use detection scheme, and when multiple daemons exist on the same machine when they can't talk to each other (referenced by the PID namespace), they start spontaneously walking all over each other.

**Comment by nazar-pc** [comment]
Have you tried Docker 1.9+ Networking feature, maybe, it can help?
Also since issue exists, whose issue is that in the first place: Ceph or Docker?
From what I've seen http://tracker.ceph.com/issues/10763 is the upstream bug, it is is closed for whatever reason without being actually resolved.
I'm pushing because building infrastructure around hacks is not good (especially using `--privileged` or `--pid=host`), I prefer resolving issues entirely.

**Comment by Ulexus** [comment]
Using a custom networking scheme (via the Docker Networking plugin, for instance) should also be a viable solution, yes.  If you have separate IP addresses for each OSD, you shouldn't be competing over the same port-stack, so you will probably be fine.

Privileged mode is mostly a problem of tracking down all the required permissions.  This is made more difficult, though, because each of the different OSD schemes require a different set of privileges.  Not only that, there are some edge cases:  running BTRFS inline OSD journals, for instance, requires some other strange permission.

That said, all of my Ceph daemons are now running without privileged mode or `--pid=host`.  If you run in `osd_directory` mode and utilize a separate journal disk/partition, you can run without `--privileged` and without `--pid=host`.

`--net=host` is still required, of course, unless you use a custom networking scheme (since the OSD must know its own IP address and that IP address must be the same IP address at which all other members of the cluster reach it).

**Comment by nazar-pc** [comment]
Thanks for explanation, my use case assumes using Ceph withing virtual network in Docker Swarm cluster using Docker Compose, so all containers will be within the same network and will have information who is where, so I think I'll not need `--net=host` either.
BTW, I have [question](https://github.com/ceph/ceph-docker/issues/176) about `osd_directory`, would be great if you can help there.

**Comment by nazar-pc** [comment]
Just for historical reference:
I'm running `osd_directory`, without `--pid=host`, without `--net=host`, without `--privileged`, but with Docker 1.9+ Networking and everything works fine with 3 ODSs even if I restart all of them together.

**Comment by leseb** [comment]
@nazar-pc so no stability issues at all? Which networking plugin do you use?

**Comment by nazar-pc** [comment]
It was testing setup on local machine, so it uses `bridge` by default, nothing serious yet. No issues when restarting one or even all OSDs together. I'll do more advanced setups with Docker Swarm cluster and `overlay` network later and definitely post updates/ reportissues if there will be something to say.
