### ISSUE TITLE
question: Ceph on Kubernetes

### ISSUE THREAD

**Issue by streamnsight** [ceph/ceph-docker#190]
why is it recommended to use --net=host and/or why is it said not to work with NAT?

I see Kubernetes just rolled out `DaemonSets` in 1.1 which is meant to deploy pods on specific nodes (or all nodes) and that seems like a better solution since the Ceph cluster can then be tracked through the K8s logging /APIs, while keeping the nodes on the internal network.

However the way this network layer is built, as I understand it, is basically NAT (I use Flannel) so does it actually work on Kubernetes with Flannel? 
I don't see a way to set --net=host for a k8s pod.

**Comment by Ulexus** [comment]
As long as all the Ceph nodes are behind the NAT and can directly address each other without NAT, you don't have to worry about NAT (since it doesn't affect them).  The Ceph daemons make a number of assumptions about their bindings, so if their advertised addresses are different from what is available to them, "bad things" will happen.  I haven't tried in several releases, so I have no idea what the current state is.

The other issue is that OSDs and _particularly_ MONs must have static IP addresses.  Ceph keeps its own internal key-value store, in addition to the configuration file, and that, as well as the MONs' clustering talk do not tolerate changing IPs (for the MONs and OSDs).

A network overlay (such as flannel) is fine, as long as:
 - all MON and OSD Ceph nodes are within the same directly-addressable network space (no NAT between them)
 - all MON and OSD Ceph nodes have static IP addresses

And yes, this is currently a sticking point for kubernetes.

**Comment by hunter** [comment]
We've been doing some testing with Ceph on Kubernetes with Flannel as the overlay. We didn't really run into any issues directly with Flannel but did find problems with MON IPs after restart since there is no guarantee about getting the same address assigned. We ended up adding a preStop hook that removes the MON and re-adding again. That means more work for the MONs but does work for most cases. The biggest issue we've found is for cases of cluster outage (all nodes down), Ceph is unable create a quorum when all nodes relaunch.

A few other things we discovered:

* Secrets are not a bad way to keep ceph configuration out of the main etcd (or running a second dedicated etcd cluster)
* Adding a Service for MONs is a useful way of avoiding hard coding IPs into the ceph.conf. The trick is to not assign an IP to the service (`clusterIP: None`) so that DNS will round robin the Pod IPs.
* OSDs aren't too picky about their IPs or Ports (at least they don't break the cluster on relaunch like the MONs)
* DaemonSets are really useful. Prior to 1.1, we were creating dedicated Pods

Our code is here (https://github.com/AcalephStorage/ceph-docker/tree/kubernetes/daemon) but its currently broken with permission issues in Infernalis.

The solution isn't as ideal as I'd like. Still a few too many rough edges. Ceph could really do with some updates to make it play nicely with dynamic infrastructure (and modern distributed KV stores).

**Comment by cornelius-keller** [comment]
Hi hunter,

I am playing around with your code. For me the issue seems if the mon did go down unexpected like when a host is rebooted during an update or if a host fails the /remove-mon.sh script might not get called. Did you have any issues like this and how did you deal with them?

**Comment by ibotty** [comment]
@streamnsight You can set `hostNetwork: true` in daemonset's `spec.template.spec`.

**Comment by Ulexus** [comment]
@ibotty @streamnsight  It should be noted, though, that as long as all of ceph is inside the kubernetes network, there should be no need for `hostNetwork: true` or `--net=host`.  There is no NAT within kubernetes.  All you have to do is make sure your monitors get static IP addresses, which you can ensure by specifying a `clusterIP` for their pods.

**Comment by ibotty** [comment]
`clusterIP` does not work with replication controllers or daemon sets though. A stable network identity is pretty hard to achieve without petsets/nominal sets.

**Comment by leseb** [comment]
Simply use the auto detection variable for the IP address. You don't need to know the ip in advance

**Comment by streamnsight** [comment]
@Ulexus 
Concur with @ibotty as far as I know you can't really specify a clusterIP on a pod. I guess you can do that on a service, which proxies to the pod, but that means one service per pod. I do that for my Zookeeper cluster because there doesn't seem to be another way. Problem is, that is not scalable. For Zookeeper, since it only requires a fixed set of pods (3 or 5 in general) so it's not a big deal, but for Ceph that is another story.

@hunter seemed to have a work-around that is the most likely solution in my opinion...
but frankly using this project has been a little too much of a pain point for my use case so I have drifted towards finding ways to mount external storage to my pods instead of trying to build the storage layer myself. 

I'd be glad to revisit when I get better assurance that this works well on Kubernetes.

**Comment by streamnsight** [comment]
@leseb, just saw your new comment: 
what exactly do you mean? That a monitor actually doesn't need a static IP? 

I'm still confused about what service does and what service doesn't need to have defined IPs. 
Daemon sets seem ideal to insure deployment on specific nodes and control the number of pods per node. That sounds great. 
Still, the IP issue is a concern. As I mentioned, In Zookeeper for example I had to proxy each node behind a specific service to guaranty that if a nodes goes down and then up somewhere else, it is still found through the service.

What happens in Ceph when a Mon or OSD goes down and changes IP? how does the discovery work in Ceph I guess? It is still confusing to me.

**Comment by ibotty** [comment]
I deploy my gluster cluster as a daemonset and host networking. That way I have a stable ip/storage-identity. Not optimal, as I don't really need host networking, but better than the alternatives.

**Comment by leseb** [comment]
Sorry I jumped to quickly on this thread. I was referring to the daemon image that detect the IP address inside the container. If all the IPs change Ceph will go down...

**Comment by cornelius-keller** [comment]
Hi all, I have been playing around a bit more with the approach @hunter . 
As I told before I had a problem when machines in the cluster where rebooting. 
If the machine gets up again, a new mon pod is started. I used deamon sets, so this mon pod has a different name and ip. In case you use replication controllers the new pod has the same name as before, but a different ip. The result is a ceph cluster with a new mon, and the old one as a zombie in down state.

The more reboots are happening the more zombie mons you have. And once they have the majority the cluster is dead.

I solved this problem by a small python script here: https://github.com/cornelius-keller/ceph-docker/blob/kubernetes/daemon/check_zombie_mons.py . I modified the entrypoint script of the daemon so that there is a new daemon monde mon_health which will run this script in a loop. The script will query both the ceph api and the kubernetes api for the current and expected monitors and then try to resolve inconsistencies by  either removing zombie monitors from ceph or delete a pod via the kubernetes api if it changed the ip.

This works well for me as long as I give the cluster some time to recover between rebooting machines. In my case the cluster takes about 5 mins to get back into a healthy state with three active mons and osds.

Currently I am working on ensuring that if my underlying coreos does reboots due to updates it does this only if the ceph cluster is in the disired healthy state.

**Comment by Ulexus** [comment]
@cornelius-keller That's very much the approach I was thinking about playing with (but never getting around to trying) for OSDs (though it sounds like it is not necessary for OSDs).   It embraces the philosophy of embracing change early so that later changes are easy, on which CoreOS is built.  I still think the monitors should probably have static IPs from the service network, but I haven't come up with a way of elegantly distributing these, without hard-coding the discrete monitors themselves (and I'm not entirely sure that's a problem, at least in my environments). 

Thanks for the feedback, and please keep us up-to-date on your progress.

**Comment by cornelius-keller** [comment]
@Ulexus I managed to find a way to securely doing coreos auto updates by adapting the "Auto-Updates with a Maintenance Window" example in https://coreos.com/os/docs/latest/update-strategies.html . Basically I use systemd to run the script not only in a window, but every 5 mins. The script than checks if ceph is in a state where it can survive one machine going down during a reboot. If this is the case it acquires a lock via locksmith and does a reboot.

Regarding the question of using service IPs for mons and OSDs I am not sure what the implications are, because the Service IP is actually not really assigned to an interface in the container, but exists only "virtualy" managed by the kube proxy (as far as I understand).
I chose to use the kubernetes cluster dns addon to do discovery of mons / osds. The problem with this is, in order to have the ceph cluster highly available I also need to have the dns ad don highly available and the kube api.

So for me the current status is that I manage to have ceph resilient to single node failures / reboots. The cluster recovers from that. 
But it is becoming unavailable if the cluster dns is not working. So my next step will be to make kubernetes itself Highly available.

**Comment by Ulexus** [comment]
@cornelius-keller No, I don't think service IPs will work.  I was talking about `clusterIP`s, which I had _thought_ were the means of exposing the _node_'s external IP address, but I am definitely wrong there.  I'm reasonably certain there is a way to do that (without resorting to host-based networking), but I cannot seem to find it, now.

**Comment by damoon** [comment]
I am running weave as the network for my containers.
The Ceph Monitors can get each a static IP via e.g. -e WEAVE_CIDR=ip:192.168.1.2/24.
The OSDs use dynamic IPs.
The Cluster runs since a few month and can do a complete shutdown&restart without problems (besides downtime).

**Comment by Ulexus** [comment]
@damoon thanks.  That is as expected, but it is good to hear confirmation.

**Comment by elsonrodriguez** [comment]
This is all pretty brilliant.

@cornelius-keller has been busy it seems, and I decided to pick up their branch to do some more polish: https://github.com/cornelius-keller/ceph-docker/pull/1

**Comment by Ulexus** [comment]
Just as a reference, it looks like PetSets are (hopefully) coming in 1.3: https://github.com/kubernetes/kubernetes/issues/260

As @ibotty mentioned, these should be the answer to the mon static IP problem.

**Comment by elsonrodriguez** [comment]
@Ulexus It doesn't look like Petsets will handle IP identity in its initial implementation, the identity will be managed by hostname.

I predict that IP identity will be a bit of bear. I've seen Kubernetes clusters that rely on host-specific pod IP ranges for networking. This means that even if IPs are a part of a pod's identity, it will only ever deploy to one node in many clusters. This kills the HA.

This will be less of a problem as K8s networking evolves, but I predict it will be a long time before most network administrators will allow k8s clusters to dynamically define routes at the pod level in their data centers, if such a thing is even desirable.

I'm going to experiment with putting CEPH MDS in a petset sometime in the next few days, but per @hunter I'm not optimistic it will work.

The mon script by @cornelius-keller is probably the best thing in the near term, and long term I think we should look at fixes in Ceph itself to make it more tolerant regarding its composability.

**Comment by Ulexus** [comment]
It was my assumption that PetSet instance IPs would be pulled from the service IP range and would, hence be both virtual and node-portable.  I have not been following the specific implementation, however, so u could certainly be wrong.

MDS daemons should have no need for PetSets, though.  They can be described simply with a headless service.

So far as I am aware, the only failing component on kubernetes is the monitor, and even that can be worked around crudely, as has been described.  PetSets, in my idealized form, would be the answer to the crudeness, generally.

I fail to see how node association violates HA, however.  After all, you should always have multiple monitors running, anyway.

**Comment by hunter** [comment]
I'm thinking PetSets with fixed IPs are less important for the MON quorum now that @cornelius-keller's mon script exists but do have some issue with the host mounts. If the MON IPs change then the mounted filesystem is unable to be updated. The workaround is using DNS although thats not available to the host unless specifically set up with SkyDNS as a resolver. Something @elsonrodriguez had highlighted in his recent PR - https://github.com/cornelius-keller/ceph-docker/pull/2/files#diff-05343bd424844a02f3f2d79117adb589R123

If PetSets are not getting fixed IPs soon then there might need to be a workaround for the host. I'm wondering how crazy the idea of using go-dnsmasq or a forked version of https://github.com/gliderlabs/resolvable to update the hosts resolv.conf to talk to SkyDNS.

**Comment by cornelius-keller** [comment]
Hello Hunter,

in my setup I configured coreos to use the cluster dns as an additional
nameserver. This seems to be a bit hacky, but works. I always use the dns
entry ceph-mon.ceph.svc.cluster.local to discover the monitor hosts.
I have a ceph setup with 5 mons and 5 osds and it seems to be pretty
robust. It just recovered from a netsplit where 2 of the machines went out
of the network.
The only thing I had to do manually was deleting some osd pods to force a
restart, because they don't seem to reconnect automatically when network
comes back. Maybe there are some additional checks needed in future for the
osds, but at least this is not as critical for the cluster health as the
mons.

I think it will be important that more people start evaluating this in
order to gain more trust into the setup and find problems. I for my part am
pretty confident, because I have set this up and rebooted machines a lot
while developing and testing this.

2016-05-20 11:24 GMT+02:00 Hunter Nield <notifications@github.com>:

**Comment by elsonrodriguez** [comment]
@Ulexus  Sorry I meant MON not MDS.

And I meant more that the resiliency would be killed rather than the HA. If you had static IPs for pods, and every node had a static pod range, and something struck all X nodes that had MONs down, even if you had 1k nodes you'd never have the mons reschedule.

In regards to PetSets, here's how it looks: https://gist.github.com/elsonrodriguez/a42c0c974c049f81302f882d63ea2b79

And here's how it behaves:

```
$ kubectl get pods -l daemon=mon --namespace=ceph
ceph-mon-0   1/1       Running   1          3m
ceph-mon-1   1/1       Running   1          3m
ceph-mon-2   1/1       Running   1          3m
```

The governing service remains the same as before:

```
$ kubectl get svc --namespace=ceph
NAME       CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
ceph-mon   None         <none>        6789/TCP   4m
```

Here's what things look like from `ceph-mon-0`:

```
root@ceph-mon-0:/# ping ceph-mon-2.ceph-mon
PING ceph-mon-2.ceph-mon.ceph.svc.cluster.local (10.244.2.5) 56(84) bytes of data.
```

`ceph-mon-2.ceph-mon` resolves to the Pod's IP (since this is and must be a headless service).

When deleting the pod, it does look like the PetSet will try to retain identity:

```
root@ceph-mon-0:/# ping ceph-mon-2.ceph-mon
PING ceph-mon-2.ceph-mon.ceph.svc.cluster.local (10.244.2.5) 56(84) bytes of data.
```

But after the application of a catastrophe to the node `ceph-mon-2` was running on:

```
root@ceph-mon-0:/# ping ceph-mon-2.ceph-mon
PING ceph-mon-2.ceph-mon.ceph.svc.cluster.local (10.244.3.7) 56(84) bytes of data.
```

If Ceph requires the IP to be static, this is a no go (until the dynamic allocation of POD IPs between nodes is a common k8s pattern).

There's also the idea of going DaemonSet+net=host. In environments with automatic node replacement/reprovisioning, in combination with @cornelius-keller 's script, we have something to think about. With the added bonus of avoiding SDN/Bridge wackiness.

@hunter Updating resolv.conf is tricky in some environments, since DHCP can have opinions on that file. Something like this would have to be done to your provisioner of choice: https://github.com/kubernetes/kubernetes/pull/25941/files

There's also a slight chance this will materialize (despite the bloat it would imply for every other FS): https://github.com/kubernetes/kubernetes/issues/23518

Additionally there was talk somewhere about putting all these utilities in the kubelet container, assuming you're using the kubelet container.

How do we feel about merging in the @cornelius-keller/@hunter [branch](https://github.com/cornelius-keller/ceph-docker/tree/kubernetes/examples/kubernetes)? It's a good step in the right direction, and we can start opening issues in a more focused approach.

**Comment by streamnsight** [comment]
@elsonrodriguez 
Thanks for the test and nice write up.

I'm still a bit confused here about the goal:
Don't we need the MON to live along with the MDS and OSD on a single node? 
So if the node dies, the OSD, MDS are gone too. 
The physical data will persists on the disk, but will not be accessible on this node until the node is back up and OSD/MDS/MON are running again. 

In your test, if I understand correctly, the IP changes because the node changes, is that right?
What if the node comes back up? Does the MON come back up on that node with the same IP?
In the end we just want to make sure the MON will have a unique IP <=> physical disk. No?
 
If a node dies, and it's gone forever, replication is to the rescue. If the node dies and comes back up, does it get the same net range and does the pod come back up with the same IP? That's what matter, i think.

Persistant IPs for pods across nodes is probably not coming anytime soon, as this is not even a Kubernetes concern: that'd be Flannel or weaver issue.

Thoughts?

**Comment by elsonrodriguez** [comment]
@streamnsight I think you'd have to consult with a Ceph expert on whether or not we need an MDS or MON per OSD.

Currently the example is setup to have just 1 MDS managed by a Deployment (this could be increased), but the MON and OSDs are in a DaemonSet, meaning every node that is tagged as "storage" will always receive one of each. Having one OSD per node makes sense, but again I defer to a Ceph expert on how many MONs are needed, and if there is such a thing as too many MONs.

Regarding node death:

- If the MON is in a PetSet, and the node is brought back up, nothing will happen.The PetSet controller would have already rescheduled the pod with the same name but a different IP. When the Pod was rescheduled it will have lost all data unless you had some other external storage. But if you're playing with Ceph then one might not be interested in a separate storage layer to back your ceph install.
- If the MON is in a Deployment, and the node is brought up, the ReplicaSet controller would have already rescheduled the pod with a random everything.
- In a Daemonset, that controller will not reschedule anything. If a node joins, it gets randomly named MON. If the downed node is brought back up, and the pod has been ejected, it gets a new randomly named MON with a random IP. That randomly named MON with the random IP will have no identity unless you used a hostPath to store whatever MONs write. But I don't know how ceph would react to to a random MON coming up with a previous incarnation's data (or an OSD for that matter)

These same concerns/concepts apply to every other component, and it's a matter of matching each component up to the best fit in Kubernetes(as @hunter and I have been trying to do), filling in the gaps with glue code (like what @cornelius-keller did), and then if up against a wall (or just fatigued with corner cases) seeing what if anything can be done upstream in Ceph itself.

**Comment by hunter** [comment]
Regarding the number of MDS and MONs required for Ceph. There is typically only a single MDS in a cluster (the HA mode isn't stable yet) and can live anywhere.

3-5 MONs should typically be run (at the very least an odd number for quorum). Anything more is not going to offer much benefit. In an ideal and high traffic implementation they should be run independently from the OSDs but in a k8s environment I think that could be left up to the scheduler. We probably should support a `monitor` label for nodes and update the Daemonset to use that.

Since any of these resources can be co-located we should set limits for CPU/Memory. Does anyone have a running cluster who can share details?

**Comment by streamnsight** [comment]
OK,
I'm still a bit confused about the whole ceph architecture, but I'm starting to get it.
So if MONs are the only problem with IPs, and there only needs to be 3-5 of them, then I think I know how to solve this: Zookeeper is the same way.

because Zookeeper only requires 3 or 5 nodes, it's not too bad of a compromise to define a Service for each Zookeeper node.
So if MONs are the same, I think the best way to work with this is to setup a headless Service per MON, with which they can talk to each other and resolve actual Pod IPs.
Then use a regular (not headless) Service per MON for the clients, so they can resolve the MON cluster even if the IP changed.
It's a little bit of a hack (I have 3 zookeeper nodes, so that's 6 Services) but that works well, and Zookeeper recovers well, without affecting clients too much (beyond the loss of communication during recovery)

Does that sound similar?

**Comment by elsonrodriguez** [comment]
If we only need 3-5 MONs then it's better to use a Deployment. When a ReplicaSet has a service associated with it, that gives strong hints to the scheduler to spread the pods across nodes.  If that's not enough then we can try Pod Antiaffinity. Then we can get rid of the node selector and just let them be anywhere in the k8s cluster.

I'm open to suggestion on resource limits. Otherwise I'm going to plug in the values I see after my next round of testing.

I can apply both of those changes early next week.

**Comment by leseb** [comment]
Kinda jumping right in this again but I'd like to clarify if possible what's needed.
As @hunter said, we need 3 to 5 monitors, we usually recommend to go with 5 when we reach petabyte scale. Everything below that should use 3 mons. Obviously monitors must run on separate host/failure domains, so might need an antiaffiinity filter for this. Having 2 mons containers ending up on the same machine is useless.

Ceph monitors have a strong dependancy with the original IP they were built from. So a monitor built with 192.168.0.1 must always run from a node with the IP 192.168.0.1, this is a **must-have**.
With k8s, the well understood issue is when we restart a POD from a failure or a just a restart, we lose this IP. This is not the only thing we loose, we are also losing the monitor directory and its content.
Here comes the tricky part:

* we assume that the infrastructure has a persistent block storage for `/var/lib/ceph/mon/<mon_id>/` and that this storage can be moved with the pod then we are good.
* we don't have persistent storage for  `/var/lib/ceph/mon/<mon_id>/` and we lost the IP, in this case we probably should re-create a new monitor.

The main problem with the second option is that we will have a list (fairly limited hopefully depending on the number of failure we are experiencing). We would need a hook in our entrypoint or a service that will look for dead monitors and just remove them.

I think we shouldn't go too far from k8s nature because of the ceph's design. k8s works the way it works, we should probably be the ones adapting instead :)

Just my 2 cents, hope it helps and clarifies the issues we have at the moment.

**Comment by elsonrodriguez** [comment]
Don't know where else to ask this, but are any of you coming to Ceph Day in Portland? I'm attending and wouldn't mind meeting up.

**Comment by leseb** [comment]
Nop I won't.

**Comment by elsonrodriguez** [comment]
@leseb Just to make sure, did you take a look at @cornelius-keller's script? It takes care of cleaning up zombie mons.

Also here's the WIP for the limits/affinity stuff.

https://github.com/elsonrodriguez/ceph-docker/commit/8458503517a6ef09e8689a789bbc72dc71717bc0

The limits are very preliminary based on light activity. Also the AntiAffinity is not working, but overall that's how the next PR to cornelius is going to look like.

**Comment by streamnsight** [comment]
btw, a little off topic, but the latest release of KViator is 0.0.5, yet I had updated it to support TLS; the PR was merged but there was no new release cut, so the scripts here probably doesn't include it.

**Comment by hunter** [comment]
Sorry about that @streamnsight, I just saw your reminder. We'll cut a release of Kviator with your TLS support and also get a fix in for the binary issue.

**Comment by elsonrodriguez** [comment]
@leseb Restarting a Pod doesn't change a pod's IP. From what I've observed a pod keeps an IP for its entire life.

This means a MON would never change its IP.

What will happen is that if a node goes down, or a cluster admin deletes a pod explicitly or via a scaling operation, a new MON will be created with a new IP and a blank slate. This MON will join the existing  quorum and things should be good.

Then something like the script cornelius wrote will go and reap dead MONs.

**Comment by natostanco** [comment]
Tried 3 services manifests containing 1mon-1osd-1mds, with `security_context privileged`, install iptables, apply a small script that brings up a loopback with the ip of the service and applies 2 rules to route traffic to such interface, specify the `MON_IP` as the ip of the service, same for `CEPH_PUBLIC_NETWORK` as the subnet of the services, then launch the entrypoint script.
Can bring the whole cluster down and up again and everything is fine with no zombies.
Initially libceph was complaining about mismatching ips because I was trying with a `lo` with an ip different from the service and routing back to the service ip but this step was not needed, time wasted.
The iptables rules are shared among all the containers in the pods.
Managed to map a rbd image and mount on coreos, write stuff, umount, delete the 3 services from kubectl, recreate them, and remount the image.

**Comment by leseb** [comment]
@elsonrodriguez thanks for the clarification.

**Comment by streamnsight** [comment]
@elsonrodriguez @leseb 

Are we talking about any Pod, or Pods in a PetSet?

I feel like @elsonrodriguez 's statement is subject to misinterpretation:
A **Pod** doesn't _restart_, but a container in a **Pod** may restart if it fails: if the process runs into an exception and exits, then the **Container** in the Pod will restart and re-join the **Pod**, keeping the same IP.

A Pod has a unique IP for all containers. It's the `pause` container that gets the IP and share it with the other containers in the **Pod** through localhost networking. 

The point here is that a Pod doesn't restart: Containers restart, but that is usually only because of the process exiting abnormally (or killing the container with docker directly on the node itself)

**Pods** are `rescheduled`. When that happens, it's because the Pod gets killed or replaced through the API or because of Node failure: the whole Pod is taken down, and could be re-assigned on any **Node**. There a new Pod is created with a new `pause` container and new IP.

Each node has a different subnet (at least with Flannel) so there is no (easy) way to keep IP across nodes when a Pod is rescheduled (which is the reason PetSets with static IP is challenging)

Even if a Pod is rescheduled on the same node, the IP would change.

If you have different information, I'd like to hear but this is my understanding.
Cheers.

**Comment by elsonrodriguez** [comment]
@streamnsight You got it right.

How do we feel about opening a pull request for this https://github.com/cornelius-keller/ceph-docker/tree/kubernetes/examples/kubernetes?

The current example is pretty dated, and @rootfs is doing some great work upstream in Kubernetes to get Ceph working better.

Might be good to move the new example in if only to increase visibility and further polish the pattern.

**Comment by leseb** [comment]
@streamnsight thanks a ton for the clarification even we wear on the same page, just some wording issue. Thanks for taking the time to put the right words :).

@elsonrodriguez @cornelius-keller any plan on pushing your recent changes on this repo?

**Comment by cornelius-keller** [comment]
@lesb I would like to see the changes in the repo, can I create a pull
request?
@elsonrodriguez <https://github.com/elsonrodriguez> do you have some more
changes that should be in there?

2016-06-08 15:55 GMT+02:00 Leseb <notifications@github.com>:

**Comment by leseb** [comment]
@cornelius-keller yes please do :), I'll be happy to have this part of the repo as well.

**Comment by elsonrodriguez** [comment]
@cornelius-keller No new changes since my last pull, we're in sync. I'll hold off on any new changes until the PR is merged.

**Comment by rootfs** [comment]
@cornelius-keller @elsonrodriguez nice job! DaemonSet is a great fit. Looking forward to your PR.

**Comment by elsonrodriguez** [comment]
In case anybody else missed it, PR has been opened for this:

https://github.com/ceph/ceph-docker/pull/318

**Comment by hunter** [comment]
@leseb / @Ulexus, should this be closed now that the PR has been merged?

**Comment by leseb** [comment]
Yes it should! Thanks for the followup @hunter
