### ISSUE TITLE
Docker  - Tag pushed images to public registry

### ISSUE THREAD

**Issue by andrewwebber** [ceph/ceph-docker#204]
I would be great if when viewing the tags for the docker images for this project that they could be correlated to the versions specified in the release notes for ceph

**Comment by tobilg** [comment]
It would be great if the process of automatic builds only for the `master` branch could be changed to manual builds, which are triggered when there's a "release" or a release-worthy version of `master`.

Otherwise, in my option using `ceph/daemon:latest` doesn't lead to reproducible containers. I have a running cluster with the version from two weeks ago, but with the version of today, I have no success...

That is a problem from my point of view.

**Comment by Ulexus** [comment]
That is an excellent idea.  We really should have been doing just that.

The problem is that the docker build right now simply pulls the latest version, so in order to do a static version which is still a "trusted build," we would have do modify the Dockerfile to pull the explicit version.  That's not a problem... we just haven't done so.

Even then, I would _prefer_ to cut an image and leave it, but as far as I know, you cannot mix manual builds into an automated build repository.

**Comment by tobilg** [comment]
Another possibility is to keep master as an automated build, and use tags to create "releases". The builds for the tags can be manually configured. That's how I handle my Docker builds for most of my images.

**Comment by h0tbird** [comment]
+1 for tagged releases and `master=latest` (I do the same thing for my containers).

**Comment by tobilg** [comment]
@leseb @Ulexus My cluster got broken due to the `latest` Docker image, after an automatic pull after a CoreOS restart after a version update. IMHO it's *really* necessary to change the way the Docker images are built/published, the sooner the better.

**Comment by fmeppo** [comment]
Is there anything I could do to help improve ceph-docker builds?   I'd like to take this toward production, and having appropriately tagged containers is a key step (one I'd be happy to work on, if possible).

**Comment by andrewwebber** [comment]
@fmeppo I would expect/like for every version you release an applicable tag could be found matching your version numbers

This would be much better than me maintaining my own
