### ISSUE TITLE
KV store support for ceph-docker/examples/coreos/tools 

### ISSUE THREAD

**Issue by xcompass** [ceph/ceph-docker#246]
Is there any plan to support KV store in  ceph-docker/examples/coreos/tools? The tools are running off ceph/base image, which doesn't pull down the configs from KV store. 

I'm thinking to use those tools in the nodes on a Kubernetes cluster running on top of CoreOS. There are some challenages (https://github.com/coreos/coreos-kubernetes/issues/287) Ideally, when kube calls rbd command, it runs the image and pull down the config from KV store and execute the rbd command.

Not sure what's the best solution. Maybe create a tools image similar to daemon image or include the KV store support in ceph/base image?

**Comment by Ulexus** [comment]
So, you're talking about pulling down a ceph config and maybe some keys from etcd, yes?  
I would think that kubernetes [secrets](https://github.com/kubernetes/kubernetes/blob/master/docs/design/secrets.md) would be a better choice for this.

Could you describe in what way the shell-based, direct-to-etcd construction routine we use in `ceph/daemon` would be preferable?

I'm certainly amenable to this proposal, I'm just not seeing a use case where it is likely to be a best practice.

**Comment by xcompass** [comment]
After looking at kube docs for rbd, it seems the feature I proposed is not need. The kube spec passes the config parameters in. 

Do you know if anyone has actually get it working on CoreOS + Kube? I'm trying it but got some errors when modprobe/mount the volume.

**Comment by Ulexus** [comment]
To my knowledge, no.  The problem is that the kubernetes implementation of rbd volumes uses the userland `rbd` tool, which does not exist on CoreOS (and shouldn't, I think).  The tools you mention here are examples to be used as the base for specific implementations.  

In my case, each of my CoreOS boxes has the required ceph config and keys installed where I can bind-mount them into place inside the script.  However, I haven't gotten around to actually testing this with kubernetes.
