### ISSUE TITLE
rbd-volume: can't mount to host filesystem/link from other containers

### ISSUE THREAD

**Issue by dmitryint** [ceph/ceph-docker#25]
I have a container with mounted RBD image as /mnt/rbd volume. Inside this container, I can see the contents of /mnt/rbd. But when I try to mount it to the host filesystem mountpoint (-v /host/path/mountpoint:/mnt/rbd) or use link to that volume from other containers with the --volumes-from Docker run option, I see only an empty directory. 
Correct me if I'm wrong, but I think it's Dockers issue that cannot pass the mount point inside the container through the -v or --volumes-from options?

**Comment by Ulexus** [comment]
Ack; now that you mentioning it, I think you are correct.  I just realized that I am not actually using it from other containers.  I will check and verify

**Comment by Ulexus** [comment]
Actually, it appears I'm not using it at all, since it is running but completely broken.

The only way this works at all is to map and unmap rbd devices... the volume stuff doesn't work at all.  I'll rework this as rbd-map and rbd-unmap, instead.  At least then you mount the rbd on the host and bind-mount those for other docker containers.
