### ISSUE TITLE
Removing the builds from master

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-docker#278]
Dear contributors,

@theanalyst ,@walkerlee ,@mbessler ,@minshenglin ,@bnoon ,@a-nldisr ,@rochaporto ,@BugRoger ,@tobilg ,@tobegit3hub ,@xcompass ,@nazar-pc ,@lorieri ,@CoRfr ,@fmeppo ,@TelanJ ,@hookenz ,@thecanadianbaker ,@rootfs ,@h0tbird ,@streamnsight ,@hunter ,@dmitryint, @Ulexus, @jimcurtis

A quick note to let you know that I'm about to remove the build for both `base` and `daemon` "latest" from the Docker Hub.
There is no point on building from master and will disrupt the dev and integration workflow.

If anyone is against the idea or using images from "latest" and needs time let me know here.
Without objection from anyone, I'll remove the build next Monday 30 May.

Thanks!

**Comment by Ulexus** [comment]
I can agree that `latest` should not build from `master`, but I wonder whether it should actually be removed.  In general, I think it should point to the most common, stable, tested OS and release.

There is certainly the problem with uncontrolled upgrades when using that link, but as long as proper tagged releases are _available_, I think the _caveat emptor_ is sufficient, when balanced against a non-functioning default.

**Comment by nazar-pc** [comment]
I think completely opposite.
Master is a latest dev build and it should be in `latest` tag. Those who want stable version should use stable tag of version they need. This is a well-known practice in Docker - always rely on stable tags in production if they are available, and use `latest` during development.

**Comment by leseb** [comment]
Hum I tend to agree with you guys even if this doesn't match with the approach we took in: https://github.com/ceph/ceph-docker/pull/277
The idea was to use `daemon` and `base` as recipients for the dev environments.
However I believe we can use another directory for this purpose and let `daemon` and `base` on master.

One thing I'm worried about is that no one is really going to push anything in master. Even if this is a best practice, I'm not sure how to include this in our workflow.

From now on people must send patch in the `ceph-releases` directory, from a subsequent branches both `daemon` and `base` will be overwritten by the content of for instance  `ceph-releases/jewel/ubuntu/14.04/{base,daemon}`.

I'm just not sure what should remain in the root of `daemon` and `base`.
I think we should consistently improve Travis's CI with more scenarios and then publish new release for all the branches.

I'm open to suggestions. :)

**Comment by Ulexus** [comment]
I don't think it should be maintained as a separate item, but simply be linked to the stable Ceph release on the most tested platform (probably ubuntu).  There's definitely an argument, as @nazar-pc says, for it being the bleeding edge dev... but with the multi-platform approach, as you say @leseb , that doesn't really mean much.

As far as how to fit that concept into Travis, though, I do not know.  I only know that that seems to be a fairly common approach among the Docker images.

**Comment by streamnsight** [comment]
my 2 cents, for what it's worth...

In the Docker worlds, `latest` is always the latest stable version, so that `docker pull <image>` without a tag pulls the latest version. 

Now, there is the issue of the various base images. For this I think it would be wise to have different image names:
`ubuntu-ceph`, `centos-ceph` etc...

if the 'recommended' base image is ubuntu, then there could be a vanilla `ceph` image which is in fact the `ubuntu-ceph` image.
A simple README can easily explain this structure so people know what they're getting and what's available.

Another approach is to tag with <base-image>-<version> and have `latest` be the recommended base image with latest version.

**Comment by fmeppo** [comment]
I'm trying to take ceph-docker to production at my site, but the current
set of branches seems extremely confusing.  As near as I can tell, there's
2 branches that matter:

jewel: current HEAD for development, what I should be using to build
production containers
master: infernalis-based HEAD, used for changes that should be backported
to 9.2.x

infernalis is a 6-month-old Infernalis-based branch that's slightly
incompatible with master, so it's probably best to avoid.  Anything older
(e.g., firefly/giant/hammer) is out-of-date upstream and should be ignored.

I have no idea what to make of everything else, but get the impression
someone else is managing changes from master/jewel into these.  In any
event, I don't think I should be basing production images off any of them.
Currently, there are no regular releases, so if I need stable snapshots I
should be using my own github fork and my own collection of docker images.
That causes some difficulty when pushing changes to one of the head
branches (in particular, daemon building from my base rather than
ceph//base) but that can be avoided with care (and testing against
ceph/base:jewel and ceph/base:latest).

Is this correct?

--
Mike Shuey

**Comment by leseb** [comment]
@streamnsight the `base` images already have a tag for each of them.

@fmeppo we are currently in the process of refactoring the branch management, please have a look at https://github.com/ceph/ceph-docker/issues/247
I'm currently writing some docs to explain the new workflow, PR here is: https://github.com/ceph/ceph-docker/pull/277
As soon as we have the process in place, we will deprecated all the current branches (jewel, infernalis, hammer, etc).

I still don't know what we should be doing when it comes to the master branch, and having or not `daemon` and `base`. I was thinking (just like @Ulexus mentioned) to point both to the latest and default path. For instance, Ceph Jewel on Ubuntu 14.04.
Now it seems that this 'mirror' is not needed since these will be available through the branch build-master-jewel-ubuntu-14.04.

The current management workflow implies that they won't be any bleeding-edge code, but only code present in all the branches. Those branches will be equivalent to 'master'.
Then when we decide that it is time to do a release, we will publish a new special tag for Jewel.

And yes, in the end, this is a lot of tags.
@nazar-pc, is this still an issue for you?

**Comment by nazar-pc** [comment]
No, I'll primarily consume stable version on Ubuntu (infernalis currently). So as soon as there is corresponding tag I'm OK with that.

**Comment by leseb** [comment]
Well, we currently have the following tags:

```
tag-build-master-hammer-centos-7
tag-build-master-hammer-ubuntu-14.04
tag-build-master-hammer-ubuntu-16.04
tag-build-master-infernalis-centos-7
tag-build-master-infernalis-ubuntu-14.04
tag-build-master-infernalis-ubuntu-16.04
tag-build-master-jewel-centos-7
tag-build-master-jewel-fedora-23
tag-build-master-jewel-ubuntu-14.04
tag-build-master-jewel-ubuntu-16.04
````

Should I conclude, you all agree that we can remove `base`, `daemon` and `demo` from master? :)

**Comment by leseb** [comment]
Thanks for +1 @nazar-pc, I'll go ahead with that.
