### ISSUE TITLE
cephx can't find osd entity name in kubernetes example when using hostPath for osd 

### ISSUE THREAD

**Issue by linekin** [ceph/ceph-docker#363]
I am using the kubernetes example.
When using hostPath for osd-directory, 
if I restart the cluster, e.g. execute `delete_ceph_cluster.sh`, then run `create_ceph_cluster.sh` again,
osd will get error message `** ERROR: osd init failed: (1) Operation not permitted`, and mon shows `cephx server osd.0: couldn't find entity name: osd.0`

I noticed that in `entrypoint.sh` osd will only execute `ceph auth add ...` when the osd directory not existed.
So if the osd directory is mounted from host, `ceph auth add ...` won't be executed when osd is restarted.
And cephx's entries is gone after mon restarted, so it can't find `osd.0`.

I tried mount `/var/lib/ceph` from host for mon, but the auth list is still not persisted.
Does cephx store the auth list on disk? Or the `entrypoint.sh` should be changed to always execute `ceph auth add ...` even if the osd directory existed?

**Comment by galexrt** [comment]
Some notes as I'm currently looking for a possible solution on this:

This seems to be more of a problem with the data dir of the Ceph Mon.
When a current Ceph Mon pod is deleted, a new one with a new name + hostname is spawned, due to the `MON_NAME` defaulting to `$(hostname -s)` a new data directory is created meaning all auth from the old mon still exists (when using a `hostDir`) but in the old directory.
Example:
```
ls /var/lib/ceph/mon/
/var/lib/ceph/mon/ceph-ceph-mon-45d32 # new Ceph Mon
/var/lib/ceph/mon/ceph-ceph-mon-67dsw # old Ceph Mon
[...]
```
