### ISSUE TITLE
Need info about nfs-ganesha.

### ISSUE THREAD

**Issue by russell-islam** [ceph/ceph-docker#410]
Could anyone please help me understand the reason why we should use nfs-ganesha? So far I can recall, last time when I used ceph-docker there was no notion of  nfs-ganesha. Thanks in advance.

**Comment by hunter** [comment]
`nfs-ganesha` can expose Ceph services (RGW and CephFS) via NFS. It means that standard tooling on clients (like Windows) can be used to mount filesystems without having to deal with keyrings or additional tools (fuse, etc).

It is not part of core Ceph and support is new in `nfs-ganesha` which is why you might not have heard of it. It is also entirely optional so you don't need to use it and the only impact is slightly larger base ceph-docker images.

**Comment by russell-islam** [comment]
Nice explanation. Thanks.
