### ISSUE TITLE
Would you publish build for Ceph released version?

### ISSUE THREAD

**Issue by hrchu** [ceph/ceph-docker#595]
It will be better if we could use the demo image in released versions, e.g., 10.2.5 and 11.2.0, instead of master build. It seems that tag-build-demo-ceph-releases-* have not be updated for a while.

**Comment by leseb** [comment]
They should be updated now.

**Comment by hrchu** [comment]
Which tag would you use for this?  tag-build-demo-ceph-releases-* still updated a years ago. https://hub.docker.com/r/ceph/demo/tags/

**Comment by leseb** [comment]
There are 12 days old now. Sorry for the delay.

**Comment by jasonrm** [comment]
The primary issue I've run into with the current image tagging scheme is unexpected upgrades. When running on Kubernetes I had a ceph pod rescheduled after running for some time (as expected). But instead of all daemons continuing to run 10.2.2 (as it was at time of initial deploy), one was silently upgraded to 10.2.5 because the image was pulled fresh on that node.

Having images tagged like `ceph/daemon:jewel-10.2.2-0-centos-7`, would greatly reduce the chance of an unplanned partial cluster upgrade.

**Comment by leseb** [comment]
Yes, I need to start pushing stable releases. Sorry about that.
Will happen soon.
