### ISSUE TITLE
Ceph AIO container

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-docker#60]
I know running multiple processes defeats Docker's philosophy but I believe some use cases might require a simple standalone container running all the Ceph processes.
Actually it's easier to bootstrap.

@Ulexus thoughts?

**Comment by Ulexus** [comment]
I'm not constitutionally opposed to multiple processes per container.  I
use them where it makes sense to do so.

Is the idea you are proposing one container that will execute whatever
components are appropriate based on configuration?  I think that's a fine
idea.

It's silly, in retrospect, that I made a while bunch of different
containers which have the exact same filesystem, save for the startup
scripts.

Also, in order to avoid the port exhaustion problem, we are already able to
run multiple daemons per container.

Finally, since we are necessarily machine-constrained, I don't think there
is much in the way of coupling purity we can cling to.

In short:  sounds good to me

**Comment by leseb** [comment]
I was initially thinking of a container that runs all the Ceph processes.
However having an image with everything installed would be nice, so we simply active the desired service.
The only drawback will probably be the size of this image.
I'll start something.

**Comment by Ulexus** [comment]
Actually, it's exactly the same as what we have now.  The ceph/base
container contains all the software.  The only difference between the
packages is the startup script, really.

**Comment by leseb** [comment]
Well everything except radosgw :).
I'll fix that in the meantime.
