### ISSUE TITLE
Would it be better to mount the OSD's inside the docker container rather than passing them through?

### ISSUE THREAD

**Issue by hookenz** [ceph/ceph-docker#77]
At the moment, ceph-osd relies on the physical ceph osd drives to be passed in via mounts which should appear under /var/lib/ceph/osd/ceph-$id

Note: The rest of this relates to running multiple OSD's in a single docker container.

Unfortunately, you can't pass a single /var/lib/ceph/osd as a host mount for all the mounts below it.  And I'm thinking that it should be possible to hotswap osd's in and out on the fly without restarting the other osd's.  Unfortunately, I don't see a way you can add volume mounts to an already running container without restarting it with the commandline changed.  And passing in a top level /var/lib/ceph/osd results in that being mounted as tmpfs which breaks things.

Maybe another approach is to change the bootstrap init script to search for block devices that have the right uuid (4fbd7e29-9d25-41b8-afd0-062c0ceff05d), mount them temporarily and read the whoami file, then mount them as the correct place internal to the image.  Then add other helpers to stop osd's, or add new ones on the fly which you can call through exec on the running ceph-osd.

I have a bash script that is already doing the osd id discovery and mounts on the outside which does that now and is based on what ceph-disk does.

If this makes any sense I'm prepared to fork this and give it a try, I'll post the results back here.

Does this seem sensible? or are there other reasons why you shouldn't mount block devices inside the container?

**Comment by Ulexus** [comment]
@hookenz I run all my OSD containers by exporting the broad-scoped `/var/lib/ceph/osd` directory (and I just updated the OSD documentation to describe this).  They are not mounted as tmpfs in any way that I can see (each of the mounts shows as either ext4 or btrfs, on my systems, both inside and outside the OSD containers).

You are certainly correct that Docker does not (yet?) have the ability to change the volume attachments to any existing container, and I haven't actually seen much movement on that limitation.

I _do_ want to change the bootstrap to be more intelligent about recognizing existing OSDs, and I think you've got a good idea, here.

I _really_ like the idea of hot adds and removes of OSDs.  That will require some thought, though.  A real problem we have right now is the limitation of needing to know the OSD number in advance.  One option is to decouple the mountpoint and directory names from the OSD ids, and just mount each OSD under /var/lib/ceph/osd as a random or UUID-based directory name.  The script could then check to see if that directory contains an initialized OSD or create a new OSD for it.

I don't think a block device search and arbitrary container-side mounting overall is a "feasible" idea, since it breaks the container separation even more, requiring the container access to the host's device tree and probably privileged mode for mounting.... but I could be swayed in that direction by something compelling.

**Comment by hookenz** [comment]
I kind of agree with you on the last point.  

In the mean time, I've discovered a hot-add mechanism which may come in handy.  <a href=http://jpetazzo.github.io/2015/01/13/docker-mount-dynamic-volumes/>Attach a volume to a container while it is running</a>

Now I've written a script that can scan for block devices that are initialized with ceph-disk prepare.
If prepared that way, then the disks will be given the part type id 4fbd7e29-9d25-41b8-afd0-062c0ceff05d.
My script will mount accordingly.  However, it mounts based on whoami file.  As the filesystem isn't created yet, they don't mount.  

So my solution is to create create another script which will wraps something along the lines of "docker run --privileged=true -v /etc/ceph:/etc/ceph -v /dev:/dev ceph/base ceph-disk prepare ..."

Then mount it by ID and add 'echo $id > /osd/id'
When ceph/osd docker image starts it'll run the ceph-osd --mkfs and --mkjournal steps to complete the process as normal.

I'm going to some more scripts to make this more seamless and help to get it running.

**Comment by Ulexus** [comment]
Closing this old issue; I believe this is archaic after the `ceph-disk` stuff
