### ISSUE TITLE
MDS names may not start with a numeric digit.

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-docker#97]
Just spotted this:

`deprecation warning: MDS id 'mds.7cf73bf1fd74' is invalid and will be forbidden in a future version.  MDS names may not start with a numeric digit.`

An easy work around could be to do something like this on the `MDS_NAME` variable: `: ${MDS_NAME:=a$(hostname -s)}`

**Comment by Ulexus** [comment]
I would slightly prefer a more mnemonic "mds-" prefix, but otherwise, that sounds like a good idea.

One thing to note, though, is that metadata servers are not machine-restricted.  They are not bound by their data directories and can move around the cluster.   As a result, I generally give mine labels like "a", "b", "c".

In this case, obviously, we cannot do that, but I wonder if adding and removing arbitrarily-named metadata servers screws with the Ceph database.

**Comment by leseb** [comment]
I like the "daemon type" prefix and I agree about the statement of volatile MDSs in general.
Perhaps we should encourage users to use `MDS_NAME` and justify this with your explanations.

Let's start by fixing this and we can always add a bit of doc later.
